### ISSUE TITLE
Plugin won't load anymore

### ISSUE THREAD

**Issue by uberhalit** [mrexodia/PasteFile#1]
I compiled the latest master with VS2022 and it compiles fine after you upgrade the build tools but the plugin itself won't get recognnized in x64dbg. I can remember I used it in the past.

**Comment by mrexodia** [comment]
What does the x64dbg log say?

**Comment by uberhalit** [comment]
```
Loading plugins...
[PLUGIN, PasteFile] Command "PasteFile" registered!
[PLUGIN] PasteFile v1 Loaded!
```
There's no entry under 'Plugins' (is there even one, I can't remember) and when I call `PasteFile` nothing happenes.

**Comment by mrexodia** [comment]
https://github.com/mrexodia/PasteFile/blob/master/PasteFile/plugin.cpp#L39

You need to pass the filepath to paste in (and select the location you wanna patch in the dump)
